---
service: notify-billing

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name:
  versionFunctions: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - ce:GetCostAndUsage
      Resource: '*'
    - Effect: Allow
      Action: ssm:GetParameter
      Resource: 'arn:aws:ssm:*:*:parameter/Slack/*/Billing/WebhookUrl'

functions:
  hello:
    handler: handler.run
    timeout: 30
    events:
      - schedule: cron(0 0 ? * MON *)
    environment: ${self:custom.environment.${self:provider.stage}}
custom:
  environment:
    dev: ${file(./env/dev.yml)}
    prod: ${file(./env/prod.yml)}
